name: creative_park
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alert_dialogs:
    git:
      url: https://github.com/LasithaPrabodha/codewithandrea_flutter_packages
      path: packages/alert_dialogs
  custom_buttons:
    git:
      url: https://github.com/LasithaPrabodha/codewithandrea_flutter_packages
      path: packages/custom_buttons
  email_password_sign_in_ui:
    git:
      url: https://github.com/LasithaPrabodha/codewithandrea_flutter_packages
      path: packages/email_password_sign_in_ui
  firestore_service:
    git:
      url: https://github.com/LasithaPrabodha/codewithandrea_flutter_packages
      path: packages/firestore_service
  equatable: ^2.0.3
  flutter_riverpod: ^0.14.0+3
  flutter_svg: ^0.22.0
  logger: ^1.0.0
  rxdart: ^0.27.1
  state_notifier: ^0.7.0
  cupertino_icons: 1.0.3
  firebase_core: 1.5.0
  firebase_auth: 3.0.2
  google_sign_in: 5.0.7
  cloud_firestore: 2.5.0
  fluttertoast: 8.0.8
  image_picker: 0.8.3
  shared_preferences: 2.0.6
  firebase_storage: 10.0.2
  intl: 0.17.0
  firebase_messaging: 10.0.5
  flutter_local_notifications: 8.1.1
  photo_view: 0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  random_string: ^2.2.0-nullsafety
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
